#!/usr/bin/env bash

function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "[%s] %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ (0 == $exitcode || 130 == $exitcode) ]]; then
        echo -e "OK!"
    else
        echo -e "Not OK!\n\n$output"
        exit 1
    fi
}

__run "1/4" "php-lint" "docker compose exec symfony php -l src/"
__run "2/4" "phpcbf" "docker compose exec symfony vendor/bin/phpcbf src/"
__run "3/4" "phpstan" "docker compose exec symfony vendor/bin/phpstan analyse"
__run "4/4" "doctrine" "docker compose exec symfony bin/console doctrine:schema:validate"

