services:
    dbtest:
        image: registry.2le.net/2le/[PROJECT]:dbtest

    symfony:
        build: .
        working_dir: /var/www/html
        ports:
            - 127.0.0.1:8000:80
        environment:
            - "COMPOSER_MEMORY_LIMIT=-1"
        depends_on:
            - dbtest
        volumes:
            - ./:/var/www/html/

    pma:
        image: phpmyadmin/phpmyadmin
        links:
            - dbtest:db
        ports:
            - "9000:80"
        environment:
            UPLOAD_LIMIT: 3000000000
            PMA_HOST: dbtest
        depends_on:
            - dbtest
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
